android.useAndroidX=true
# Desativado para ganhar performance, reative se algum plugin Cordova antigo falhar
android.enableJetifier=false
android.suppressUnsupportedCompileSdk=35

# Otimizações para CI e Build local
org.gradle.jvmargs=-Xmx2048m -Dfile.encoding=UTF-8
org.gradle.parallel=true
org.gradle.caching=true
org.gradle.configureondemand=true
