// Strings para internacionalização (PT-BR)
export const strings = {
  // Login
  login_title: "Entrar",
  login_sub: "Faça login para continuar",
  login_email_placeholder: "Email ou usuário",
  login_password_placeholder: "Senha",
  login_button: "Entrar",
  login_guest: "Entrar como convidado",
  register_button: "Criar conta",
  forgot_password: "Esqueci minha senha",
  pin_prompt: "Digite seu PIN",
  biometric_prompt: "Autentique com biometria",
  
  // Logout
  logout_confirm_title: "Sair da conta?",
  logout_confirm_text: "Deseja realmente sair? Você continuará com os dados locais salvos.",
  logout_button: "Sair",
  delete_account_confirm: "Apagar conta e todos os dados locais?",
  
  // Tema
  theme_toggle: "Tema escuro",
  
  // Progresso
  initial_progress_label: "0 ml / {meta} ml",
  add_success: "Registrado: +{ml} ml",
  undo: "Desfazer",
  
  // Registro
  register_title: "Criar Conta",
  register_sub: "Crie sua conta para salvar dados",
  register_name_placeholder: "Nome completo",
  register_email_placeholder: "Email (opcional)",
  register_password_placeholder: "Senha (mín. 6 caracteres)",
  register_confirm_password_placeholder: "Confirmar senha",
  register_weight_placeholder: "Peso (kg)",
  register_age_placeholder: "Idade",
  register_sex_label: "Sexo",
  register_success: "Conta criada com sucesso!",
  
  // Onboarding
  onboarding_welcome_title: "Bem-vindo ao Hydropush!",
  onboarding_welcome_sub: "Vamos configurar seu perfil",
  onboarding_goal_title: "Sua Meta Diária",
  onboarding_goal_sub: "Baseada no seu perfil",
  onboarding_notifications_title: "Lembretes",
  onboarding_notifications_sub: "Permita notificações para lembretes",
  onboarding_complete: "Começar",
  
  // Erro genérico
  error_generic: "Algo deu errado. Tente novamente.",
  error_network: "Erro de conexão. Verifique sua internet.",
  error_validation: "Por favor, verifique os dados informados.",
  
  // Sucesso
  success_goal_updated: "Meta atualizada com sucesso!",
  success_profile_updated: "Perfil atualizado!",
  success_data_exported: "Dados exportados com sucesso!",
  success_data_imported: "Dados importados com sucesso!",
  
  // Navegação
  nav_home: "Início",
  nav_stats: "Estatísticas", 
  nav_profile: "Perfil",
  nav_history: "Histórico",
  nav_settings: "Configurações",
  
  // Saudações
  greeting_morning: "Bom dia",
  greeting_afternoon: "Boa tarde", 
  greeting_evening: "Boa noite",
  
  // Dashboard
  dashboard_start_day: "Vamos começar o dia!",
  dashboard_start_sub: "Sua jornada de hidratação começa agora",
  dashboard_continue: "Continue assim!",
  dashboard_continue_sub: "Você está no caminho certo",
  dashboard_goal_today: "Meta de hoje:",
  dashboard_start_tip: "Comece com um copo d'água!",
  dashboard_quick_add: "Adicionar rapidamente",
  dashboard_custom: "Personalizar",
  dashboard_custom_amount: "Quantidade personalizada (ml)",
  dashboard_custom_placeholder: "Ex: 300",
  dashboard_custom_add: "Adicionar",
  dashboard_today: "Hoje",
  dashboard_no_entries: "Ainda não registrou hoje",
  dashboard_lets_drink: "Vamos beber?",
  dashboard_total_consumed: "Total consumido",
  dashboard_goal_reached: "Meta alcançada!",
  dashboard_goal_reached_sub: "Parabéns, você bateu sua meta de hoje!",
  dashboard_remaining: "Faltam {amount}ml",
  
  // Configurações
  settings_notifications: "Notificações e Lembretes",
  settings_push_notifications: "Notificações Push",
  settings_push_sub: "Receber lembretes de hidratação",
  settings_sound: "Som",
  settings_sound_sub: "Reproduzir som na notificação",
  settings_vibration: "Vibração", 
  settings_vibration_sub: "Vibrar ao receber notificação",
  settings_smart_reminders: "Lembretes Inteligentes",
  settings_smart_sub: "Ajustar baseado na sua rotina",
  settings_reminder_config: "Configurações de Lembrete",
  settings_reminder_interval: "Intervalo entre Lembretes",
  settings_quiet_hours: "Horário Silencioso",
  settings_quiet_start: "Início",
  settings_quiet_end: "Fim",
  settings_quiet_description: "Durante este período você não receberá lembretes",
  settings_weekend_reminders: "Lembretes no Final de Semana",
  settings_weekend_sub: "Enviar lembretes sábado e domingo",
  settings_data_privacy: "Dados e Privacidade",
  settings_local_data: "Dados Locais",
  settings_local_sub: "Todos os seus dados ficam armazenados localmente no dispositivo. Nenhuma informação é enviada para servidores externos.",
  settings_export: "Exportar Dados",
  settings_import: "Importar Dados",
  settings_appearance: "Aparência",
  settings_theme_dark: "Tema Escuro",
  settings_theme_light: "Tema Claro",
  settings_theme_color: "Cor do Tema",
  settings_theme_blue: "Azul Água (Padrão)",
  settings_account: "Conta",
  settings_logged_as: "Logado como:",
  settings_logout: "Sair da Conta",
  settings_delete_account: "Apagar Conta e Dados",
  
  // Intervalos de lembrete
  interval_30min: "30 minutos",
  interval_1h: "1 hora", 
  interval_1h30: "1,5 hora",
  interval_2h: "2 horas",
  interval_3h: "3 horas",
  
  // Perfil
  profile_title: "Perfil",
  profile_sub: "Gerencie suas informações e metas",
  profile_user: "Usuário Hydropush",
  profile_today_goal: "Meta Hoje",
  profile_daily_goal: "Meta Diária",
  profile_personal_info: "Informações Pessoais",
  profile_weight: "Peso (kg)",
  profile_height: "Altura (m)",
  profile_age: "Idade",
  profile_activity: "Atividade",
  profile_routine: "Rotina:",
  profile_wake_time: "Acordar",
  profile_sleep_time: "Dormir",
  profile_goal_section: "Meta Diária",
  profile_current_goal: "Meta diária atual",
  profile_edit: "Editar",
  profile_save: "Salvar",
  profile_cancel: "Cancelar",
  profile_recommended: "Recomendado:",
  profile_based_profile: "Baseado no seu perfil",
  profile_progress: "Progresso:",
  profile_goal_achieved: "da meta alcançada",
  profile_adjust_suggestion: "Sua meta atual difere da recomendação.",
  profile_adjust_question: "Ajustar para {amount}L?",
  profile_achievements: "Conquistas",
  profile_first_goal: "Primeira Meta",
  profile_7_days: "7 Dias Seguidos",
  profile_perfect_week: "Semana Perfeita",
  
  // Histórico
  history_title: "Histórico",
  history_sub: "Acompanhe seu progresso ao longo do tempo",
  history_day: "Dia",
  history_week: "Semana", 
  history_month: "Mês",
  history_week_summary: "Resumo desta Semana",
  history_total_intake: "Ingestão Total",
  history_average: "Média:",
  history_goal_average: "Média da Meta",
  history_days: "dias",
  history_weekly_chart: "Gráfico Semanal",
  history_consumed: "Consumido",
  history_goal: "Meta",
  history_trend: "Tendência de Hidratação",
  history_average_progress: "Progresso médio:",
  history_achievements: "Conquistas",
  history_first_day: "Primeiro dia",
  history_3_days: "3 dias",
  history_1_week: "1 semana",
  history_today: "Hoje",
  history_yesterday: "Ontem",
  history_goal_met: "Meta alcançada",
  history_remaining: "Faltam {amount}ml",
  history_monthly_view: "Visualização Mensal",
  history_monthly_soon: "Em breve! Análises mensais detalhadas com insights personalizados.",
  history_dev_feature: "Funcionalidade em desenvolvimento",
  history_load_more: "Carregar Mais Histórico",
  
  // Estatísticas
  stats_title: "Estatísticas",
  stats_sub: "Acompanhe seu progresso",
  stats_insight_excellent: "Excelente! Meta alcançada!",
  stats_insight_almost: "Quase lá! Falta pouco.",
  stats_insight_halfway: "No meio do caminho.",
  stats_insight_accelerate: "Vamos acelerar a hidratação!",
  stats_weekly_average: "Média semanal:",
  stats_daily_average: "Média Diária",
  stats_per_day: "por dia",
  stats_streak: "Sequência",
  stats_consecutive_days: "dias consecutivos",
  stats_total_week: "Total Semana",
  stats_this_week: "esta semana",
  stats_today: "Hoje",
  stats_goal_reached: "da meta alcançada",
  stats_weekly_progress: "Progresso Semanal",
  stats_trend: "Tendência de Hidratação",
  stats_achievements: "Conquistas",
  
  // Atividades físicas
  activity_sedentary: "Sedentária",
  activity_light: "Leve", 
  activity_moderate: "Moderada",
  activity_intense: "Intensa",
  activity_very_intense: "Muito Intensa",
  
  // Sexo
  sex_male: "M",
  sex_female: "F", 
  sex_other: "Outro",
  
  // Guest mode
  guest_mode: "Modo Convidado",
  guest_mode_sub: "Dados ficam locais no dispositivo",
  guest_create_account: "Crie uma conta para salvar seus dados",
  
  // Versão
  app_version: "Versão 2.2.0",
  app_tagline: "Mantenha-se hidratado, mantenha-se saudável!",
  app_developed: "Desenvolvido com ❤️ para sua saúde"
};